server:
  port: 8082
spring:
  kafka:
    #    consumer:
    #      auto-offset-reset: earliest
    #      bootstrap-servers: localhost:29092
    #      group-id: some-group-id
    #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    #      properties:
    #        spring.json.trusted.packages: com.n1nt3nd0.kafkaspringbootexample.event # change this with your event packages
    producer:
      ## 0 -- none / 1 -- leader / -1 -- all
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
  #    default-schema: puplic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600 #seconds
  issuer: avraam112russo
