
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
server:
  port: 8094
  tomcat:
    max-swallow-size: 100MB
#  spring.servlet.multipart.max-file-size=100MB
#  spring.servlet.multipart.max-request-size=100MB
#  server.tomcat.max-swallow-size=100MB

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: mysecretpassword
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml




#  data:
#    redis:
#      host: localhost
#      port: 6379
